import { SearchItem } from "./types";

export const GUIDE_SEARCH_ITEMS: SearchItem[] = [
  {
    id: "guide-install",
    title: "Installation & Module Setup",
    category: "Guides",
    description: "go get github.com/shishir1290/gsocketio@latest with zero external module dependencies.",
    href: "#steps",
    keywords: ["install", "installation", "go get", "setup", "module", "dependencies", "zero dependencies", "standard library"],
    badge: "Step 01",
  },
  {
    id: "guide-minimal",
    title: "Minimal Server & Connection Lifecycle",
    category: "Guides",
    description: "Spin up a high-performance Socket.IO v4 server in under 20 lines with sio.New(nil).",
    href: "#steps",
    keywords: ["server", "minimal", "quickstart", "onconnect", "ondisconnect", "onevent", "listen", "http", "net/http"],
    badge: "Step 02",
  },
  {
    id: "guide-auth",
    title: "Authentication & Context Management",
    category: "Guides",
    description: "Access client auth tokens (JWT/API keys), attach request context, and validate credentials on connect.",
    href: "#steps",
    keywords: ["auth", "authentication", "jwt", "token", "context", "setcontext", "getcontext", "headers", "security"],
    badge: "Step 03",
  },
  {
    id: "guide-namespaces",
    title: "Namespaces & Multi-Tenancy",
    category: "Guides",
    description: "Segment real-time communication into isolated namespaces with distinct handler trees.",
    href: "#steps",
    keywords: ["namespaces", "namespace", "multi-tenancy", "routing", "isolation", "dynamic namespace", "custom path"],
    badge: "Step 04",
  },
  {
    id: "guide-rooms",
    title: "Rooms & Targeted Event Broadcasting",
    category: "Guides",
    description: "Group connections dynamically into rooms (c.Join, c.Leave) and broadcast targeted messages (srv.To).",
    href: "#steps",
    keywords: ["rooms", "room", "broadcast", "broadcasting", "join", "leave", "targeted", "chat", "multicast", "to"],
    badge: "Step 05",
  },
  {
    id: "guide-acks",
    title: "Client-Server Event Acknowledgments (Acks)",
    category: "Guides",
    description: "Request request-response confirmation with binary/string acknowledgments across socket frames.",
    href: "#steps",
    keywords: ["acknowledgments", "ack", "callbacks", "rpc", "confirmation", "response", "request response"],
    badge: "Step 06",
  },
  {
    id: "guide-binary",
    title: "Binary Buffers & Raw Data Streaming",
    category: "Guides",
    description: "Stream raw bytes ([]byte, Uint8Array, ArrayBuffer) efficiently with zero base64 transcoding overhead.",
    href: "#steps",
    keywords: ["binary", "buffer", "raw data", "streaming", "uint8array", "arraybuffer", "bytes", "blob", "audio", "video"],
    badge: "Step 07",
  },
  {
    id: "guide-config",
    title: "Production Tuning & Server Config",
    category: "Guides",
    description: "Configure PingInterval, PingTimeout, MaxPayload, AllowUpgrades, CORS policies, and connection pools.",
    href: "#steps",
    keywords: ["config", "configuration", "production", "pinginterval", "pingtimeout", "maxpayload", "cors", "tuning", "performance"],
    badge: "Step 08",
  },
];
