import { SearchItem } from "./types";

export const OVERVIEW_SEARCH_ITEMS: SearchItem[] = [
  {
    id: "overview-home",
    title: "gsocketio Overview & High Throughput",
    category: "Overview",
    description: "Zero-dependency pure-Go Socket.IO v4 server with maximum throughput and client compatibility.",
    href: "#",
    keywords: ["home", "overview", "intro", "performance", "features", "throughput", "golang", "socket.io", "v4"],
    badge: "v1.0.4",
  },
  {
    id: "overview-compare",
    title: "Go Socket Ecosystem Benchmark & Comparison",
    category: "Overview",
    description: "Compare gsocketio vs Legacy go-socket.io vs Gorilla WebSocket vs net/http across features and latency.",
    href: "#compare",
    keywords: ["compare", "comparison", "benchmark", "gorilla", "performance", "latency", "features"],
    badge: "Benchmark",
  },
  {
    id: "overview-architecture",
    title: "Architecture & Flow Graph",
    category: "Overview",
    description: "Interactive architectural flow graph showing transport upgrades, session manager, rooms, and packet codecs.",
    href: "#architecture",
    keywords: ["architecture", "flow", "graph", "diagram", "transport", "polling", "websocket", "codec", "concurrency"],
    badge: "Interactive",
  },
  {
    id: "overview-protocol",
    title: "Engine.IO & Socket.IO Wire Protocol",
    category: "Protocol",
    description: "Interactive step-by-step trace of Engine.IO v4 handshakes, ping/pong heartbeats, and packet framing.",
    href: "#protocol",
    keywords: ["protocol", "engine.io", "socket.io", "wire", "packet", "frame", "handshake", "ping", "pong", "upgrade"],
  },
  {
    id: "overview-simulator",
    title: "Live WebSocket Simulator Playground",
    category: "Overview",
    description: "Test real-time packet exchange, event emissions, latency benchmarks, and room broadcasting in the browser.",
    href: "#playground",
    keywords: ["simulator", "playground", "test", "websocket", "latency", "benchmark", "emit", "broadcast", "packets"],
    badge: "Live Tool",
  },
  {
    id: "overview-faq",
    title: "Frequently Asked Questions (FAQ)",
    category: "Overview",
    description: "Technical answers on Socket.IO v4 client compatibility, zero dependencies, benchmarks, auth, and RFC 6455.",
    href: "#faq",
    keywords: ["faq", "questions", "answers", "gorilla", "performance", "jwt", "auth", "binary", "compatibility"],
    badge: "FAQ",
  },
];
