import { SearchItem } from "./types";

export const SDK_API_SEARCH_ITEMS: SearchItem[] = [
  // Client SDKs
  {
    id: "sdk-js",
    title: "JavaScript / TypeScript / React Client",
    category: "Client SDKs",
    description: "Connect from Next.js, React, Node.js, and browser using socket.io-client v4.",
    href: "#clients",
    keywords: ["javascript", "typescript", "react", "next.js", "node.js", "socket.io-client", "npm", "browser", "frontend"],
    badge: "JS / TS",
  },
  {
    id: "sdk-python",
    title: "Python Socket.IO Client",
    category: "Client SDKs",
    description: "Connect using python-socketio with asyncio or synchronous client sockets.",
    href: "#clients",
    keywords: ["python", "python-socketio", "asyncio", "django", "fastapi", "flask", "ai", "machine learning"],
    badge: "Python",
  },
  {
    id: "sdk-flutter",
    title: "Flutter & Dart Client",
    category: "Client SDKs",
    description: "Cross-platform mobile & desktop client integration using socket_io_client for Flutter.",
    href: "#clients",
    keywords: ["flutter", "dart", "mobile", "ios", "android", "socket_io_client", "cross-platform"],
    badge: "Flutter",
  },
  {
    id: "sdk-swift",
    title: "Swift (iOS / macOS) Client",
    category: "Client SDKs",
    description: "Native iOS, iPadOS, and macOS integration with SocketIO-Kit / Socket.IO-Client-Swift.",
    href: "#clients",
    keywords: ["swift", "ios", "macos", "apple", "xcode", "socket.io-client-swift", "mobile"],
    badge: "Swift",
  },
  {
    id: "sdk-kotlin",
    title: "Kotlin & Android Client",
    category: "Client SDKs",
    description: "Native Android application client utilizing socket.io-client-java in Kotlin coroutines.",
    href: "#clients",
    keywords: ["kotlin", "android", "java", "coroutines", "mobile", "socket.io-client-java"],
    badge: "Kotlin",
  },
  {
    id: "sdk-unity",
    title: "Unity (C#) Game Engine Client",
    category: "Client SDKs",
    description: "Real-time multiplayer synchronization and game networking in Unity with C# SocketIO.",
    href: "#clients",
    keywords: ["unity", "c#", "csharp", "game", "gamedev", "multiplayer", "unity3d", "gaming"],
    badge: "Unity C#",
  },

  // API Reference
  {
    id: "api-server",
    title: "Server API (sio.Server)",
    category: "API Reference",
    description: "sio.New, srv.OnConnect, srv.OnEvent, srv.OnDisconnect, srv.Broadcast, srv.To, srv.ServeHTTP.",
    href: "#api",
    keywords: ["server", "api", "sio.new", "onconnect", "ondisconnect", "onevent", "broadcast", "to", "servehttp", "methods"],
    badge: "Go Struct",
  },
  {
    id: "api-conn",
    title: "Connection API (sio.Conn)",
    category: "API Reference",
    description: "c.ID(), c.Namespace(), c.Emit(), c.Join(), c.Leave(), c.Rooms(), c.Context(), c.SetContext(), c.Close().",
    href: "#api",
    keywords: ["conn", "connection", "socket", "emit", "join", "leave", "rooms", "context", "setcontext", "id", "close"],
    badge: "Go Interface",
  },
  {
    id: "api-config",
    title: "Configuration API (sio.Config)",
    category: "API Reference",
    description: "PingInterval, PingTimeout, MaxPayload, AllowUpgrades, Transports, OriginFunc, BufferSize.",
    href: "#api",
    keywords: ["config", "options", "pinginterval", "pingtimeout", "maxpayload", "transports", "cors", "originfunc"],
    badge: "Go Struct",
  },

  // Community & Portfolio
  {
    id: "community-github",
    title: "GitHub Repository (shishir1290/gsocketio)",
    category: "Community",
    description: "View open-source source code, star the project, report issues, and submit pull requests.",
    href: "https://github.com/shishir1290/gsocketio",
    keywords: ["github", "git", "source", "star", "repo", "repository", "issues", "pr", "open source"],
    badge: "GitHub",
    isExternal: true,
  },
  {
    id: "community-pkg",
    title: "pkg.go.dev Documentation",
    category: "Community",
    description: "Official Go package reference index, signatures, examples, and godoc documentation.",
    href: "https://pkg.go.dev/github.com/shishir1290/gsocketio",
    keywords: ["pkg.go.dev", "godoc", "docs", "go package", "reference", "library"],
    badge: "Go Docs",
    isExternal: true,
  },
  {
    id: "community-portfolio",
    title: "Developer Portfolio — Md. Sadmanur Islam Shishir",
    category: "Community",
    description: "Explore creator portfolio, projects, contact, and tech stack (Primary: shishir.click | Mirror: shishir1290.netlify.app).",
    href: "/portfolio",
    keywords: ["portfolio", "shishir", "developer", "author", "creator", "shishir.click", "sadmanur", "contact", "about"],
    badge: "shishir.click",
    isExternal: true,
  },
];
