export interface SearchItem {
  id: string;
  title: string;
  category: "Overview" | "Guides" | "Client SDKs" | "API Reference" | "Protocol" | "Community";
  description: string;
  href: string;
  keywords: string[];
  badge?: string;
  isExternal?: boolean;
}

export const SEARCH_INDEX: SearchItem[] = [
  // Overview
  {
    id: "overview-home",
    title: "gsocketio Overview & High Throughput",
    category: "Overview",
    description: "Zero-dependency pure-Go Socket.IO v4 server with maximum throughput and client compatibility.",
    href: "#",
    keywords: ["home", "overview", "intro", "performance", "features", "throughput", "golang", "socket.io", "v4"],
    badge: "v1.0.4",
  },
  {
    id: "overview-architecture",
    title: "Architecture & Flow Graph",
    category: "Overview",
    description: "Interactive architectural flow graph showing transport upgrades, session manager, rooms, and packet codecs.",
    href: "#architecture",
    keywords: ["architecture", "flow", "graph", "diagram", "transport", "polling", "websocket", "codec", "concurrency"],
    badge: "Interactive",
  },
  {
    id: "overview-protocol",
    title: "Engine.IO & Socket.IO Wire Protocol",
    category: "Protocol",
    description: "Interactive step-by-step trace of Engine.IO v4 handshakes, ping/pong heartbeats, and packet framing.",
    href: "#protocol",
    keywords: ["protocol", "engine.io", "socket.io", "wire", "packet", "frame", "handshake", "ping", "pong", "upgrade"],
  },
  {
    id: "overview-simulator",
    title: "Live WebSocket Simulator Playground",
    category: "Overview",
    description: "Test real-time packet exchange, event emissions, latency benchmarks, and room broadcasting in the browser.",
    href: "#playground",
    keywords: ["simulator", "playground", "test", "websocket", "latency", "benchmark", "emit", "broadcast", "packets"],
    badge: "Live Tool",
  },

  // Guides & Recipes
  {
    id: "guide-install",
    title: "Installation & Module Setup",
    category: "Guides",
    description: "go get github.com/shishir1290/gsocketio@latest with zero external module dependencies.",
    href: "#steps",
    keywords: ["install", "installation", "go get", "setup", "module", "dependencies", "zero dependencies", "standard library"],
    badge: "Step 01",
  },
  {
    id: "guide-minimal",
    title: "Minimal Server & Connection Lifecycle",
    category: "Guides",
    description: "Spin up a high-performance Socket.IO v4 server in under 20 lines with sio.New(nil).",
    href: "#steps",
    keywords: ["server", "minimal", "quickstart", "onconnect", "ondisconnect", "onevent", "listen", "http", "net/http"],
    badge: "Step 02",
  },
  {
    id: "guide-auth",
    title: "Authentication & Context Management",
    category: "Guides",
    description: "Access client auth tokens (JWT/API keys), attach request context, and validate credentials on connect.",
    href: "#steps",
    keywords: ["auth", "authentication", "jwt", "token", "context", "setcontext", "getcontext", "headers", "security"],
    badge: "Step 03",
  },
  {
    id: "guide-namespaces",
    title: "Namespaces & Multi-Tenancy",
    category: "Guides",
    description: "Segment real-time communication into isolated namespaces with distinct handler trees.",
    href: "#steps",
    keywords: ["namespaces", "namespace", "multi-tenancy", "routing", "isolation", "dynamic namespace", "custom path"],
    badge: "Step 04",
  },
  {
    id: "guide-rooms",
    title: "Rooms & Targeted Event Broadcasting",
    category: "Guides",
    description: "Group connections dynamically into rooms (c.Join, c.Leave) and broadcast targeted messages (srv.To).",
    href: "#steps",
    keywords: ["rooms", "room", "broadcast", "broadcasting", "join", "leave", "targeted", "chat", "multicast", "to"],
    badge: "Step 05",
  },
  {
    id: "guide-acks",
    title: "Client-Server Event Acknowledgments (Acks)",
    category: "Guides",
    description: "Request request-response confirmation with binary/string acknowledgments across socket frames.",
    href: "#steps",
    keywords: ["acknowledgments", "ack", "callbacks", "rpc", "confirmation", "response", "request response"],
    badge: "Step 06",
  },
  {
    id: "guide-binary",
    title: "Binary Buffers & Raw Data Streaming",
    category: "Guides",
    description: "Stream raw bytes ([]byte, Uint8Array, ArrayBuffer) efficiently with zero base64 transcoding overhead.",
    href: "#steps",
    keywords: ["binary", "buffer", "raw data", "streaming", "uint8array", "arraybuffer", "bytes", "blob", "audio", "video"],
    badge: "Step 07",
  },
  {
    id: "guide-config",
    title: "Production Tuning & Server Config",
    category: "Guides",
    description: "Configure PingInterval, PingTimeout, MaxPayload, AllowUpgrades, CORS policies, and connection pools.",
    href: "#steps",
    keywords: ["config", "configuration", "production", "pinginterval", "pingtimeout", "maxpayload", "cors", "tuning", "performance"],
    badge: "Step 08",
  },

  // Client SDKs
  {
    id: "sdk-js",
    title: "JavaScript / TypeScript / React Client",
    category: "Client SDKs",
    description: "Connect from Next.js, React, Node.js, and browser using socket.io-client v4.",
    href: "#clients",
    keywords: ["javascript", "typescript", "react", "next.js", "node.js", "socket.io-client", "npm", "browser", "frontend"],
    badge: "JS / TS",
  },
  {
    id: "sdk-python",
    title: "Python Socket.IO Client",
    category: "Client SDKs",
    description: "Connect using python-socketio with asyncio or synchronous client sockets.",
    href: "#clients",
    keywords: ["python", "python-socketio", "asyncio", "django", "fastapi", "flask", "ai", "machine learning"],
    badge: "Python",
  },
  {
    id: "sdk-flutter",
    title: "Flutter & Dart Client",
    category: "Client SDKs",
    description: "Cross-platform mobile & desktop client integration using socket_io_client for Flutter.",
    href: "#clients",
    keywords: ["flutter", "dart", "mobile", "ios", "android", "socket_io_client", "cross-platform"],
    badge: "Flutter",
  },
  {
    id: "sdk-swift",
    title: "Swift (iOS / macOS) Client",
    category: "Client SDKs",
    description: "Native iOS, iPadOS, and macOS integration with SocketIO-Kit / Socket.IO-Client-Swift.",
    href: "#clients",
    keywords: ["swift", "ios", "macos", "apple", "xcode", "socket.io-client-swift", "mobile"],
    badge: "Swift",
  },
  {
    id: "sdk-kotlin",
    title: "Kotlin & Android Client",
    category: "Client SDKs",
    description: "Native Android application client utilizing socket.io-client-java in Kotlin coroutines.",
    href: "#clients",
    keywords: ["kotlin", "android", "java", "coroutines", "mobile", "socket.io-client-java"],
    badge: "Kotlin",
  },
  {
    id: "sdk-unity",
    title: "Unity (C#) Game Engine Client",
    category: "Client SDKs",
    description: "Real-time multiplayer synchronization and game networking in Unity with C# SocketIO.",
    href: "#clients",
    keywords: ["unity", "c#", "csharp", "game", "gamedev", "multiplayer", "unity3d", "gaming"],
    badge: "Unity C#",
  },

  // API Reference
  {
    id: "api-server",
    title: "Server API (sio.Server)",
    category: "API Reference",
    description: "sio.New, srv.OnConnect, srv.OnEvent, srv.OnDisconnect, srv.Broadcast, srv.To, srv.ServeHTTP.",
    href: "#api",
    keywords: ["server", "api", "sio.new", "onconnect", "ondisconnect", "onevent", "broadcast", "to", "servehttp", "methods"],
    badge: "Go Struct",
  },
  {
    id: "api-conn",
    title: "Connection API (sio.Conn)",
    category: "API Reference",
    description: "c.ID(), c.Namespace(), c.Emit(), c.Join(), c.Leave(), c.Rooms(), c.Context(), c.SetContext(), c.Close().",
    href: "#api",
    keywords: ["conn", "connection", "socket", "emit", "join", "leave", "rooms", "context", "setcontext", "id", "close"],
    badge: "Go Interface",
  },
  {
    id: "api-config",
    title: "Configuration API (sio.Config)",
    category: "API Reference",
    description: "PingInterval, PingTimeout, MaxPayload, AllowUpgrades, Transports, OriginFunc, BufferSize.",
    href: "#api",
    keywords: ["config", "options", "pinginterval", "pingtimeout", "maxpayload", "transports", "cors", "originfunc"],
    badge: "Go Struct",
  },

  // Community & Portfolio
  {
    id: "community-github",
    title: "GitHub Repository (shishir1290/gsocketio)",
    category: "Community",
    description: "View open-source source code, star the project, report issues, and submit pull requests.",
    href: "https://github.com/shishir1290/gsocketio",
    keywords: ["github", "git", "source", "star", "repo", "repository", "issues", "pr", "open source"],
    badge: "GitHub",
    isExternal: true,
  },
  {
    id: "community-pkg",
    title: "pkg.go.dev Documentation",
    category: "Community",
    description: "Official Go package reference index, signatures, examples, and godoc documentation.",
    href: "https://pkg.go.dev/github.com/shishir1290/gsocketio",
    keywords: ["pkg.go.dev", "godoc", "docs", "go package", "reference", "library"],
    badge: "Go Docs",
    isExternal: true,
  },
  {
    id: "community-portfolio",
    title: "Developer Portfolio — Md. Sadmanur Islam Shishir",
    category: "Community",
    description: "Explore creator portfolio, projects, contact, and tech stack (Primary: shishir.click | Mirror: shishir1290.netlify.app).",
    href: "/portfolio",
    keywords: ["portfolio", "shishir", "developer", "author", "creator", "shishir.click", "sadmanur", "contact", "about"],
    badge: "shishir.click",
    isExternal: true,
  },
];
